### ISSUE TITLE
Plays statistic

### ISSUE THREAD

**Issue by andriusmickus** [Progrunning/BoardGamesCompanion#243]
This app is lovely and very easy to use, however what im really missing is some statistic reports.
Are there any plans to add statistic overview, where it would be possible to see which games where played most during the month/year. Also statistic about players and which players has won most of the games. Maybe some kind of top5, top10 list?

**Comment by mkieres** [comment]
hey @andriusmickus, these are popular request/feedback that I'm hearing from the users. The overall stats #74 (that's how I call it) is something that I'll be working on next. If you're interested in what's in the "pipeline" you can have a look at this board https://github.com/orgs/Progrunning/projects/1/views/1. I try to keep it up to date but it might not be always reflecting the truth.

If you don't mind I'll close this issue (to avoid duplicates) but feel free to comment on the above or #164 for players stats, if you have any other suggestions than what's already captured in them. I'll definitely take into consideration what you have written in this issue as well.
