### ISSUE TITLE
Ability to upload plays to bgg

### ISSUE THREAD

**Issue by vogella** [Progrunning/BoardGamesCompanion#245]
Currently the app seems to be use only read-access to BGG. Would it be possible to also add upload of played games to bgg?

Sorry, if that has already been reported, I could not find a related issue to that.

**Comment by mkieres** [comment]
Hey @vogella , I've heard this request/feedback multiple times. I would love to add that feature in but unfortunately it won't be possible until BGG exposes an official API to sign users in. You can read a bit more about this problem in the Wiki https://github.com/Progrunning/BoardGamesCompanion/wiki/Features#bgg-integration.

I'll close this issue as I don't think this will be possible anytime soon.

**Comment by vogella** [comment]
Thanks @mkieres for the answer, sorry to hear that there is not yet an official API for this.
