### ISSUE TITLE
Improve entering points experience

### ISSUE THREAD

**Issue by mkieres** [Progrunning/BoardGamesCompanion#70]
# Ideas

## Circular picker
Use a `+` and `-` button to show a circular number picker and add or subtract respectively the number picked on the wheel

Examples:
- https://pub.dev/packages/progressive_time_picker
- https://pub.dev/packages/time_range_picker

## Circular action menu
Use a `+` and `-` button to expand more buttons in a circle. These buttons would be +1, +2, +3, +5, +10 etc.

Examples 
- https://pub.dev/packages/circular_menu
- https://pub.dev/packages/flutter_radial_menu

**Comment by BAT754** [comment]
Hey, just wanted to pop in here and say that the new "point entering" UI is really good! Wanted to make sure I used it plenty before giving some feedback. It is very smooth, and I actually like it a lot more than a standard keyboard entry. Great job!

**Comment by mkieres** [comment]
Hey @BAT754, thanks a lot for you feedback. I'm glad to hear that you're liking it. It was a bit of a gamble on my end because I don't have proper testing group of users and wasn't sure if it's going to work for others. I did a bit of a research on the entering points apps and the spinning wheel and `+` and `-` quick buttons seemed to be the highest ranked and rated apps.
