### ISSUE TITLE
No score entered for player causes errors with stats

### ISSUE THREAD

**Issue by BAT754** [Progrunning/BoardGamesCompanion#85]
Small bug to report.
 
Environment Details:
iPhone X
OS: iOS 15.3.1
App: v1.5.897

Issue:
When entering scores for players, an issue occurs when a player scores no points, and no score is entered for that player. 
When at the point enter screen, any player that hasn't had their points edited yet shows 0 points. But when the scores are saved, the history page will show the score as "-", instead of 0. 
Then, on the stats page of that game, the "games won by player" pie chart incorrectly shows that the player with "-" score has won a game.

![Logged Game](https://user-images.githubusercontent.com/55164875/155921944-bc80c057-7db8-4b13-bfbf-ee948dfb2207.jpeg)
![Overall Stats](https://user-images.githubusercontent.com/55164875/155921941-8ba87dd4-83d4-4aa5-af1a-a142756b522a.jpeg)

I've attempted to attach two pictures (sorry about the huge size) that should help visualize the issue. The logged game picture shows a logged game with the player Ben scoring 10 points, and the player Macy scoring "-" points, due to no score being entered for them. Yet in the Overall Stats picture, you can see that in the chart, Macy is shown to have won 100% of the games, and not Ben.

Small issue that can be fixed by adding one point, and then subtracting one point from the player that should have 0 points. But figured it was worth mentioning as a bug.

**Comment by mkieres** [comment]
@BAT754 This bug should be now fixed with the latest version of the app released today (`1.5.930`). If you are still seeing the problem I'll reopen the issues
